### ISSUE TITLE
Minecraft 1.16.4 Fabric server Crash on startup

### ISSUE THREAD

**Issue by roachard** [RakambdaOrg/EditSign#12]
**Describe the bug**
Crashes at startup on fabric server.

**To Reproduce**
1. Move jar to mods folder
2. Startup server

**Infos:**
 - Minecraft verson: 1.16.4
 - Fabric version: 0.6.1.51
 - Mod version: Fabric-1.16.3-2.1.3
 - No other mods installed on the server

Crash log:
```[06:05:33] [main/INFO]: Loading for game Minecraft 1.16.4
[06:05:34] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: edit_sign requires {fabric @ [*]}
at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:173) ~[fabric-server-launch.jar:?]
at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:739) ~[fabric-server-launch.jar:?]
at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:210) ~[fabric-server-launch.jar:?]
at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:200) [fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:128) [fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27) [fabric-server-launch.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-server-launch.jar:?]
at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-server-launch.jar:?]
at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-server-launch.jar:?]
at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-server-launch.jar:?]
at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:170) ~[fabric-server-launch.jar:?]```

**Comment by Rakambda** [comment]
Did you put [fabric-api](https://www.curseforge.com/minecraft/mc-mods/fabric-api) into your mods folder?

**Comment by roachard** [comment]
That did the trick, thanks! I assumed that a Fabric server would already have the Fabric API installed natively
