### ISSUE TITLE
Plugin doesn't load at all

### ISSUE THREAD

**Issue by d00mfish** [RakambdaOrg/EditSign#2]
**Describe the bug**
Plugin won't load due to a missing plugin.yml

**To Reproduce**
1. Put plugin in Plugin folder
2. start server

**Infos:**
 - Minecraft verson: 1.16.1 - Paper-31
 - Mod version: 2.0.0+7

```
>.... [11:16:36 ERROR]: Could not load 'plugins/EditSign-1.16.1-2.0.0+7.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[patched_1.16.1.jar:git-Paper-31]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:148) ~[patched_1.16.1.jar:git-Paper-31]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.loadPlugins(CraftServer.java:386) ~[patched_1.16.1.jar:git-Paper-31]
at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:208) ~[patched_1.16.1.jar:git-Paper-31]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-31]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-31]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
... 7 more
```

**Comment by Rakambda** [comment]
This is a Forge mod, not a Bukkit/Spigot/Paper plugin.

**Comment by d00mfish** [comment]
Oh wow jokes on me. Sorry
